spring:
  ai:
    mcp:
      server:
        name: bungo-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        # stdio
        stdio: true

  main:
    web-application-type: none
    banner-mode: off